### ISSUE TITLE
envoy-workshop-basics_upstream doesn't start due to   Werkzeug 3.0.0 was released and Flask doesn't specify the dependency correctly

### ISSUE THREAD

**Issue by abulanov** [solo-io/envoy-workshop-basics#15]
$ docker logs 6d5ea1f1921d
Traceback (most recent call last):
  File "/app/service/server.py", line 1, in <module>
    from flask import Flask, request, abort
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)__

**Comment by den-is** [comment]
I had to fix issue using this:
```sh
docker-compose down --rmi=all -v --remove-orphans
docker system prune -f
sed -i "s/^RUN.*/RUN pip3 install 'Werkzeug==2.2.2' 'Flask==2.0.3'/" ~/envoy-workshop-basics/upstream/service/Dockerfile ~/envoy-workshop-basics/auth/service/Dockerfile
BUILDKIT_PROGRESS=plain docker-compose up --build --force-recreate --no-deps -d
```

Feel free to add `-q` to pip install and remove `BUILDKIT_PROGRESS=plain` before docker-compose up

**Comment by asayah** [comment]
fixed
